x-spark-common:
  &spark-common
  image: bitnami/spark:3.5.6
  networks:
    - cdp-net
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8000:8080"
    environment:
      SPARK_MODE: "master"

  spark-worker:
    <<: *spark-common
    container_name: spark-worker
    ports:
      - "8001:8081"
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://spark-master:7077"
      SPARK_WORKER_MEMORY: "1G"
      SPARK_WORKER_CORES: 1
    depends_on:
      - spark-master


  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    container_name: minio
    volumes:
      - ./docker-data/minio:/data
    environment:
      MINIO_ROOT_USER: "minio"  # This is access key
      MINIO_ROOT_PASSWORD: "minio1234@abc" # This is secret key
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - cdp-net
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nifi:
    image: apache/nifi:2.4.0
    container_name: nifi
    volumes:
      - ./docker-data/nifi_data/database_repository:/opt/nifi/nifi-current/database_repository
      - ./docker-data/nifi_data/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./docker-data/nifi_data/state:/opt/nifi/nifi-current/state
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: "nifi"
      SINGLE_USER_CREDENTIALS_PASSWORD: "nifi1234567Az!"
    command: >
      bash -c "
      sleep 10 &&
      sed -i 's|^#\(nifi.python.command=.*\)|\1|' /opt/nifi/nifi-current/conf/nifi.properties &&
      /opt/nifi/bin/nifi.sh run"
    networks:
      - cdp-net

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    volumes:
      - ./docker-data/kafka:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9094:9094"
      - "9092:9092"
    networks:
      - cdp-net

networks:
  cdp-net:
    driver: bridge